export const ROUTER_ABI = [
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_factory",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"_WCLO",
        "type":"address"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"constructor"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":false,
        "internalType":"address",
        "name":"_sender",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"address",
        "name":"_tokenA",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"address",
        "name":"_tokenB",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"uint256",
        "name":"_amountA",
        "type":"uint256"
      },
      {
        "indexed":false,
        "internalType":"uint256",
        "name":"_amountB",
        "type":"uint256"
      }
    ],
    "name":"AddLiquidity",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":false,
        "internalType":"address",
        "name":"_sender",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"address",
        "name":"_tokenA",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"address",
        "name":"_tokenB",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"uint256",
        "name":"_amountA",
        "type":"uint256"
      },
      {
        "indexed":false,
        "internalType":"uint256",
        "name":"_amountB",
        "type":"uint256"
      }
    ],
    "name":"RemoveLiquidity",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":false,
        "internalType":"address",
        "name":"_sender",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"address",
        "name":"_tokenIn",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"address",
        "name":"_tokenOut",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"uint256",
        "name":"_amountIn",
        "type":"uint256"
      },
      {
        "indexed":false,
        "internalType":"uint256",
        "name":"_amountOut",
        "type":"uint256"
      }
    ],
    "name":"Swap",
    "type":"event"
  },
  {
    "inputs":[

    ],
    "name":"WCLO",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"tokenA",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"tokenB",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"amountADesired",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountBDesired",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountAMin",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountBMin",
        "type":"uint256"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"addLiquidity",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"amountA",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountB",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"liquidity",
        "type":"uint256"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"token",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"amountTokenDesired",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountTokenMin",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountCLOMin",
        "type":"uint256"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"addLiquidityCLO",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"amountToken",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountCLO",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"liquidity",
        "type":"uint256"
      }
    ],
    "stateMutability":"payable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "name":"balanceERC223",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"",
        "type":"uint256"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"factory",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountOut",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"reserveIn",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"reserveOut",
        "type":"uint256"
      }
    ],
    "name":"getAmountIn",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"amountIn",
        "type":"uint256"
      }
    ],
    "stateMutability":"pure",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountIn",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"reserveIn",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"reserveOut",
        "type":"uint256"
      }
    ],
    "name":"getAmountOut",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"amountOut",
        "type":"uint256"
      }
    ],
    "stateMutability":"pure",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountOut",
        "type":"uint256"
      },
      {
        "internalType":"address[]",
        "name":"path",
        "type":"address[]"
      }
    ],
    "name":"getAmountsIn",
    "outputs":[
      {
        "internalType":"uint256[]",
        "name":"amounts",
        "type":"uint256[]"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountIn",
        "type":"uint256"
      },
      {
        "internalType":"address[]",
        "name":"path",
        "type":"address[]"
      }
    ],
    "name":"getAmountsOut",
    "outputs":[
      {
        "internalType":"uint256[]",
        "name":"amounts",
        "type":"uint256[]"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"msgSender",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountA",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"reserveA",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"reserveB",
        "type":"uint256"
      }
    ],
    "name":"quote",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"amountB",
        "type":"uint256"
      }
    ],
    "stateMutability":"pure",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"tokenA",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"tokenB",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"liquidity",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountAMin",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountBMin",
        "type":"uint256"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"removeLiquidity",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"amountA",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountB",
        "type":"uint256"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"token",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"liquidity",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountTokenMin",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountCLOMin",
        "type":"uint256"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"removeLiquidityCLO",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"amountToken",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountCLO",
        "type":"uint256"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"token",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"liquidity",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountTokenMin",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountCLOMin",
        "type":"uint256"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"removeLiquidityCLOSupportingFeeOnTransferTokens",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"amountCLO",
        "type":"uint256"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"token",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"liquidity",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountTokenMin",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountCLOMin",
        "type":"uint256"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      },
      {
        "internalType":"bool",
        "name":"approveMax",
        "type":"bool"
      },
      {
        "internalType":"uint8",
        "name":"v",
        "type":"uint8"
      },
      {
        "internalType":"bytes32",
        "name":"r",
        "type":"bytes32"
      },
      {
        "internalType":"bytes32",
        "name":"s",
        "type":"bytes32"
      }
    ],
    "name":"removeLiquidityCLOWithPermit",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"amountToken",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountCLO",
        "type":"uint256"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"token",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"liquidity",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountTokenMin",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountCLOMin",
        "type":"uint256"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      },
      {
        "internalType":"bool",
        "name":"approveMax",
        "type":"bool"
      },
      {
        "internalType":"uint8",
        "name":"v",
        "type":"uint8"
      },
      {
        "internalType":"bytes32",
        "name":"r",
        "type":"bytes32"
      },
      {
        "internalType":"bytes32",
        "name":"s",
        "type":"bytes32"
      }
    ],
    "name":"removeLiquidityCLOWithPermitSupportingFeeOnTransferTokens",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"amountCLO",
        "type":"uint256"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"tokenA",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"tokenB",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"liquidity",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountAMin",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountBMin",
        "type":"uint256"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      },
      {
        "internalType":"bool",
        "name":"approveMax",
        "type":"bool"
      },
      {
        "internalType":"uint8",
        "name":"v",
        "type":"uint8"
      },
      {
        "internalType":"bytes32",
        "name":"r",
        "type":"bytes32"
      },
      {
        "internalType":"bytes32",
        "name":"s",
        "type":"bytes32"
      }
    ],
    "name":"removeLiquidityWithPermit",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"amountA",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountB",
        "type":"uint256"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountOut",
        "type":"uint256"
      },
      {
        "internalType":"address[]",
        "name":"path",
        "type":"address[]"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"swapCLOForExactTokens",
    "outputs":[
      {
        "internalType":"uint256[]",
        "name":"amounts",
        "type":"uint256[]"
      }
    ],
    "stateMutability":"payable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountOutMin",
        "type":"uint256"
      },
      {
        "internalType":"address[]",
        "name":"path",
        "type":"address[]"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"swapExactCLOForTokens",
    "outputs":[
      {
        "internalType":"uint256[]",
        "name":"amounts",
        "type":"uint256[]"
      }
    ],
    "stateMutability":"payable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountOutMin",
        "type":"uint256"
      },
      {
        "internalType":"address[]",
        "name":"path",
        "type":"address[]"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"swapExactCLOForTokensSupportingFeeOnTransferTokens",
    "outputs":[

    ],
    "stateMutability":"payable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountIn",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountOutMin",
        "type":"uint256"
      },
      {
        "internalType":"address[]",
        "name":"path",
        "type":"address[]"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"swapExactTokensForCLO",
    "outputs":[
      {
        "internalType":"uint256[]",
        "name":"amounts",
        "type":"uint256[]"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountIn",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountOutMin",
        "type":"uint256"
      },
      {
        "internalType":"address[]",
        "name":"path",
        "type":"address[]"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"swapExactTokensForCLOSupportingFeeOnTransferTokens",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountIn",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountOutMin",
        "type":"uint256"
      },
      {
        "internalType":"address[]",
        "name":"path",
        "type":"address[]"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"swapExactTokensForTokens",
    "outputs":[
      {
        "internalType":"uint256[]",
        "name":"amounts",
        "type":"uint256[]"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountIn",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountOutMin",
        "type":"uint256"
      },
      {
        "internalType":"address[]",
        "name":"path",
        "type":"address[]"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"swapExactTokensForTokensSupportingFeeOnTransferTokens",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountOut",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountInMax",
        "type":"uint256"
      },
      {
        "internalType":"address[]",
        "name":"path",
        "type":"address[]"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"swapTokensForExactCLO",
    "outputs":[
      {
        "internalType":"uint256[]",
        "name":"amounts",
        "type":"uint256[]"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"amountOut",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"amountInMax",
        "type":"uint256"
      },
      {
        "internalType":"address[]",
        "name":"path",
        "type":"address[]"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"deadline",
        "type":"uint256"
      }
    ],
    "name":"swapTokensForExactTokens",
    "outputs":[
      {
        "internalType":"uint256[]",
        "name":"amounts",
        "type":"uint256[]"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"tokenAddress",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_from",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"_value",
        "type":"uint256"
      },
      {
        "internalType":"bytes",
        "name":"_data",
        "type":"bytes"
      }
    ],
    "name":"tokenReceived",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"token",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"amount",
        "type":"uint256"
      }
    ],
    "name":"withdraw",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "stateMutability":"payable",
    "type":"receive"
  }
] as const;
